# Server configuration
server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/ # Directory where Thymeleaf templates are located
    suffix: .html # File extension for the templates
  datasource:
    url: jdbc:sqlserver://DESKTOP-K6I7727\\InstanceName:1433;databaseName=mydb;encrypt=true;trustServerCertificate=true;
    username: sqlcoadmin
    password: 123123123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
