server:
  port: 8080

spring:
  main:
    lazy-initialization: true
  thymeleaf:
    prefix: classpath:/web/
    suffix: .html
  datasource:
    url: jdbc:sqlserver://DESKTOP-K6I7727\\InstanceName:1433;databaseName=mydb;encrypt=true;trustServerCertificate=true;
    username: sqlcoadmin     #DESKTOP-QIEQGCN #DESKTOP-K6I7727
    password: 123123123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  web:
    resources:
      cache:
        period: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
