server:
  port: 8080

spring:
  main:
    lazy-initialization: true
  thymeleaf:
    prefix: classpath:/web/
    suffix: .html
  datasource:
      url:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  web:
    resources:
      cache:
        period: 0
  cache:
    cache-names: myCache
    caffeine:
      spec: maximumSize=500,expireAfterAccess=10m


jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
